### ISSUE TITLE
Surface Tools - asset loading not work

### ISSUE THREAD

**Issue by thx114** [AlphaGaming7780/ExtraLandscapingTools-BepInEx#1]
There seems to be an issue with asset loading in the mod you created, similar to the problem with the ExtendedRoadUpgrades mod:
https://github.com/ST-Apps/CS2-ExtendedRoadUpgrades/issues/8

For some users (almost 50%), after installing your mod, Surface Tools is not appearing as expected (see Image 1), and the issue persists regardless of attempts to resolve it, unless they switch to a different computer.

Image 1
![image](https://github.com/AlphaGaming7780/ExtraLandscapingTools/assets/52259890/6bb1c195-78bf-4825-8566-c171842341d2)

**Comment by AlphaGaming7780** [comment]
So I made this pre-release, if you can try it and tell me if it's working now ?
https://github.com/AlphaGaming7780/ExtraLandscapingTools/releases/tag/v0.1.3-pre-1

**Comment by AlphaGaming7780** [comment]
Fixed in v0.1.3
