### ISSUE TITLE
Issue with motorcycles after installation

### ISSUE THREAD

**Issue by DJTSmith18** [AlphaGaming7780/ExtraLandscapingTools-BepInEx#3]
After installation of this mod, motorcycle riders freeze when getting off after parking, this causes major traffic issues as this jams up the whole road until camera is zoomed in on the problem motorcycle.  this seamingly has nothing to do with your intended purpose of this mod, but it is breaking games. on Reddit so far, I have found 3 other people with this issue... uninstalling this mod resolves all issues.

**Comment by AlphaGaming7780** [comment]
The mod does nothing with the pathfinding or stuff like that. So I can't do something about that.

**Comment by DJTSmith18** [comment]
I did extensive debugging with the devtools, it is not a pathfinding issue... it seams to be an animation issue or something of that sort. the pathfinding works but the driver of the motorcycle's animation freezes/bugs until the camera is zoomed in on it, then everything continues to function after that... the pathfinding remains correct... I noticed your code does reference the camera, I suspect it has more to do with that.

**Comment by AlphaGaming7780** [comment]
All the camera related code is comment, so it's not in the release. So your version of the mod doesn't have this code.
