### ISSUE TITLE
Suggestion: Show markers option in the landscaping tools menu

### ISSUE THREAD

**Issue by Haneybd87** [AlphaGaming7780/ExtraLandscapingTools-BepInEx#4]
Yenyang may also be contacting you about this too, but a toggle in the extra landscaping tools menu for show markers would be highly useful for placing surfaces down to create custom roads, paths, and parking lots.

**Comment by AlphaGaming7780** [comment]
This option is already added in the 0.2.0 pre- release version.

But I only add the option in the surface menu, do you want it somewhere else ?  
(note that if you show the markers in the surfaces menu, the markers stay on screen when you leave the surfaces menu)

**Comment by Haneybd87** [comment]
Ah ok, I was not aware of it being in the pre-release version.

**Comment by AlphaGaming7780** [comment]
If you want, you can try the pre-release version, it's stable and have no critical bugs, or you wait for the final release.
Here is the link to the latest pre-release if you want to try : https://github.com/AlphaGaming7780/ExtraLandscapingTools/releases/tag/v0.2.0-pre-5

**Comment by Haneybd87** [comment]
Thanks, I’ll give it a try.

**Comment by Haneybd87** [comment]
Hey I'm checking out the pre-release version. I like the markers option and also the decals are a nice edition. I am wondering about the park area/hangaround area/walking area option. Is there some trick to get these to work? Because as far as I can tell, outside of an actual park they don't work.

**Comment by AlphaGaming7780** [comment]
I try a lot of stuff with these areas and these are only work in building. So you can use these areas on building, but outside of it they don't work.

If you want to use the walking area, you can use the invisible path or the invisible pedestrian road.

To have access to these assets you download this ELT Extension also in pre-release, you need to have anarchy for now to avoid issue. The extension : https://github.com/AlphaGaming7780/ELT-Assets/releases is really in development, but it adds a lot of cool things, if you have suggestion about it, I'm open.
You need to use the latest pre-release of ELT ([v0.2.0-pre-7](https://github.com/AlphaGaming7780/ExtraLandscapingTools/releases/tag/v0.2.0-pre-7))
